services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: logistics
      POSTGRES_USER: logistics_user
      POSTGRES_PASSWORD: logistics_pass
    ports:
      - '5432:5432'