apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
  namespace: logistics-platform
data:
  DB_HOST: postgres
  DB_PORT: '5432'
  DB_USER: logistics_user
  DB_PASSWORD: logistics_pass
  DB_NAME: logistics
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: '5672'
  RABBITMQ_USER: logistics_user
  RABBITMQ_PASSWORD: logistics_pass

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
  namespace: logistics-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
    spec:
      containers:
        - name: inventory-api
          image: logistics-platform:latest
          imagePullPolicy: Never # For minikube
          command: ['node', 'dist/apps/inventory/backend/start.js']
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: inventory-config
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-api
  namespace: logistics-platform
spec:
  selector:
    app: inventory-api
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
